// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tracking.Infrastructure.Persistence;

#nullable disable

namespace Tracking.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TrackingDbContext))]
    [Migration("20260926180654_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tracking.Domain.Entities.HistorialEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EstadoAnterior")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_anterior");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_nuevo");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cambio");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origen");

                    b.Property<int>("PaqueteId")
                        .HasColumnType("integer")
                        .HasColumnName("paquete_id");

                    b.HasKey("Id")
                        .HasName("pk_historial_estados");

                    b.HasIndex("PaqueteId")
                        .HasDatabaseName("ix_historial_estados_paquete_id");

                    b.ToTable("historial_estados", (string)null);
                });

            modelBuilder.Entity("Tracking.Domain.Entities.Paquete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("cliente");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("direccion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_asignacion");

                    b.Property<string>("Guia")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("guia");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<int>("PilotoId")
                        .HasColumnType("integer")
                        .HasColumnName("piloto_id");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_actualizacion");

                    b.Property<string>("Zona")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("zona");

                    b.HasKey("Id")
                        .HasName("pk_paquetes");

                    b.HasIndex("Guia")
                        .IsUnique()
                        .HasDatabaseName("ix_paquetes_guia");

                    b.HasIndex("PilotoId")
                        .HasDatabaseName("ix_paquetes_piloto_id");

                    b.ToTable("paquetes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cliente = "Ferretería El Constructor",
                            Direccion = "12 Calle 4-50 Zona 10",
                            Estado = "PENDIENTE",
                            FechaAsignacion = new DateTime(2026, 9, 26, 14, 0, 0, 0, DateTimeKind.Utc),
                            Guia = "GUA-10001",
                            PilotoId = 1,
                            Telefono = "5555-1234",
                            UltimaActualizacion = new DateTime(2026, 9, 26, 14, 0, 0, 0, DateTimeKind.Utc),
                            Zona = "Zona 10"
                        },
                        new
                        {
                            Id = 2,
                            Cliente = "Farmacia La Salud",
                            Direccion = "6a Avenida 8-20 Zona 1",
                            Estado = "EN_RUTA",
                            FechaAsignacion = new DateTime(2026, 9, 26, 14, 0, 0, 0, DateTimeKind.Utc),
                            Guia = "GUA-10002",
                            PilotoId = 1,
                            Telefono = "5555-2345",
                            UltimaActualizacion = new DateTime(2026, 9, 26, 14, 0, 0, 0, DateTimeKind.Utc),
                            Zona = "Zona 1"
                        },
                        new
                        {
                            Id = 3,
                            Cliente = "Librería Cervantes",
                            Direccion = "Calzada Roosevelt 22-43 Zona 11",
                            Estado = "ENTREGADO",
                            FechaAsignacion = new DateTime(2026, 9, 26, 14, 0, 0, 0, DateTimeKind.Utc),
                            Guia = "GUA-10003",
                            PilotoId = 1,
                            Telefono = "5555-3456",
                            UltimaActualizacion = new DateTime(2026, 9, 26, 14, 0, 0, 0, DateTimeKind.Utc),
                            Zona = "Zona 11"
                        },
                        new
                        {
                            Id = 4,
                            Cliente = "Supermercado Don Pedro",
                            Direccion = "Boulevard Los Próceres 18-60 Zona 10",
                            Estado = "NO_ENTREGADO",
                            FechaAsignacion = new DateTime(2026, 9, 26, 14, 0, 0, 0, DateTimeKind.Utc),
                            Guia = "GUA-10004",
                            Observaciones = "Cliente ausente, se dejó aviso",
                            PilotoId = 1,
                            Telefono = "5555-4567",
                            UltimaActualizacion = new DateTime(2026, 9, 26, 14, 0, 0, 0, DateTimeKind.Utc),
                            Zona = "Zona 10"
                        },
                        new
                        {
                            Id = 5,
                            Cliente = "Panadería San Martín",
                            Direccion = "Avenida Petapa 45-12 Zona 12",
                            Estado = "PENDIENTE",
                            FechaAsignacion = new DateTime(2026, 9, 26, 14, 0, 0, 0, DateTimeKind.Utc),
                            Guia = "GUA-10005",
                            PilotoId = 2,
                            Telefono = "5555-5678",
                            UltimaActualizacion = new DateTime(2026, 9, 26, 14, 0, 0, 0, DateTimeKind.Utc),
                            Zona = "Zona 12"
                        },
                        new
                        {
                            Id = 6,
                            Cliente = "Óptica Visión Clara",
                            Direccion = "7a Avenida 3-33 Zona 9",
                            Estado = "EN_RUTA",
                            FechaAsignacion = new DateTime(2026, 9, 26, 14, 0, 0, 0, DateTimeKind.Utc),
                            Guia = "GUA-10006",
                            PilotoId = 2,
                            UltimaActualizacion = new DateTime(2026, 9, 26, 14, 0, 0, 0, DateTimeKind.Utc),
                            Zona = "Zona 9"
                        },
                        new
                        {
                            Id = 7,
                            Cliente = "Taller Mecánico Rápido",
                            Direccion = "Calzada Aguilar Batres 34-70 Zona 11",
                            Estado = "PENDIENTE",
                            FechaAsignacion = new DateTime(2026, 9, 26, 14, 0, 0, 0, DateTimeKind.Utc),
                            Guia = "GUA-10007",
                            PilotoId = 2,
                            Telefono = "5555-7890",
                            UltimaActualizacion = new DateTime(2026, 9, 26, 14, 0, 0, 0, DateTimeKind.Utc),
                            Zona = "Zona 11"
                        },
                        new
                        {
                            Id = 8,
                            Cliente = "Tienda Deportiva Campeón",
                            Direccion = "20 Calle 10-15 Zona 15",
                            Estado = "ENTREGADO",
                            FechaAsignacion = new DateTime(2026, 9, 26, 14, 0, 0, 0, DateTimeKind.Utc),
                            Guia = "GUA-10008",
                            PilotoId = 2,
                            Telefono = "5555-8901",
                            UltimaActualizacion = new DateTime(2026, 9, 26, 14, 0, 0, 0, DateTimeKind.Utc),
                            Zona = "Zona 15"
                        });
                });

            modelBuilder.Entity("Tracking.Domain.Entities.Piloto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_pilotos");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_pilotos_codigo");

                    b.ToTable("pilotos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Codigo = "PIL-001",
                            Nombre = "Carlos Méndez"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Codigo = "PIL-002",
                            Nombre = "Ana López"
                        });
                });

            modelBuilder.Entity("Tracking.Domain.Entities.HistorialEstado", b =>
                {
                    b.HasOne("Tracking.Domain.Entities.Paquete", "Paquete")
                        .WithMany("Historial")
                        .HasForeignKey("PaqueteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_historial_estados_paquetes_paquete_id");

                    b.Navigation("Paquete");
                });

            modelBuilder.Entity("Tracking.Domain.Entities.Paquete", b =>
                {
                    b.HasOne("Tracking.Domain.Entities.Piloto", "Piloto")
                        .WithMany("Paquetes")
                        .HasForeignKey("PilotoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_paquetes_pilotos_piloto_id");

                    b.Navigation("Piloto");
                });

            modelBuilder.Entity("Tracking.Domain.Entities.Paquete", b =>
                {
                    b.Navigation("Historial");
                });

            modelBuilder.Entity("Tracking.Domain.Entities.Piloto", b =>
                {
                    b.Navigation("Paquetes");
                });
#pragma warning restore 612, 618
        }
    }
}
